# This workflow will build the LearnKeys Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
    
    - name: Make build script executable
      run: chmod +x LearnKeys/build.sh
      
    - name: Build LearnKeys
      run: |
        cd LearnKeys
        ./build.sh
    
    - name: Verify build output
      run: |
        if [ -f "LearnKeys/build/LearnKeys" ]; then
          echo "✅ Build artifact created successfully"
          ls -la LearnKeys/build/LearnKeys
        else
          echo "❌ Build artifact not found"
          exit 1
        fi
    
    - name: Run tests
      run: |
        chmod +x LearnKeys/Tests/test_build.sh
        cd LearnKeys
        Tests/test_build.sh
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: LearnKeys-executable
        path: LearnKeys/build/LearnKeys
